import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect, useState } from "react";
import { createViewport } from "@shapediver/viewer";
import SdSession from "../src/components/SdSession";
import SdSessionInputs from "../src/components/SdSessionInputs";

export default function Home() {
    const benchTicket = "a55628b5ccd16762870d14a6b168bea5406430694548998adf76678109dc658425c26671339b29e8d8688fe65757e3a3e117d55b60f63e0c73fe02ffd1e1e402d3b2173b163dd6e20782b6ea7d162d32e411e01101d6ce48c137c0a7e4f9e95b3d2c8cec128aec-a5cb37cb7caefba26adf6519b71ace17-3a01cf3d24f8366dd64a0e2dfce4d4fc";
    const benchUrl = "https://sdeuc1.eu-central-1.shapediver.com";
    
    const shelfTicket = 'a55628b5ccd16762870d14a6b168bea5406430694548998adf76678109dc658425c26671339b29e8d8688fe65757e3a3e117d55b60f63e0c73fe02ffd1e1e402d3b2173b163dd6e20782b6ea7d162d32e411e01101d6ce48c137c0a7e4f9e95b3d2c8cec128aec-a5cb37cb7caefba26adf6519b71ace17-ebeca640b168d58d6712919abc886168';
    const shelfUrl = 'https://sdeuc1.eu-central-1.shapediver.com';
    
    const [ticket, setTicket] = useState(benchTicket);
    const [modelViewUrl, setModelViewUrl] = useState(benchUrl);

    const loadShapediverViewport = async () => {
        const viewport = await createViewport({
            canvas: document.getElementById("canvas") as HTMLCanvasElement,
            id: "myViewport",
        });
    };

    useEffect(() => {
        loadShapediverViewport();
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Manglar Madre Design Explorer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.header}>
                <div className={styles.title}>
                    Welcome to{" "}
                    <a href="https://en.wikipedia.org/wiki/Tulum">
                        Manglar Madre
                    </a>
                </div>
            </div>
            <div className={styles.gridLayout}>
                <div className={styles.canvasContainer}>
                    <canvas className={styles.canvas} id="canvas"></canvas>
                </div>
                <div className={styles.inputsContainer}>
                    <SdSession
                        ticket={ticket}
                        modelViewUrl={modelViewUrl}
                    >
                        {/* 
                        TODO: Additional components to pull in from the example if we want to enable model interaction
                        <SdSessionInteractionData level={interactionLevel} interactionTypes={interactionTypes}/>
                        <SdSessionParameterBridge/>
                        <SdSessionParameterPanel/> 
                    */}
                        <SdSessionInputs/>
                    </SdSession>
                </div>
            </div>
            <div className={styles.tableContainer}> Future Table Container </div>
        </div>
    );
}
