import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect, useState } from "react";
import { createViewport } from "@shapediver/viewer";
import SdSession from "../src/components/SdSession";
import SdSessionInputs from "../src/components/SdSessionInputs";

export default function Home() {
    const benchTicket = "bdf4391107cb5bf8c8bc941193ee42f52d3cfedbddf4fc8bb8bb42c7112de5efa3c13d218c1a723acf11f056e7db5086445c8b0d765029c550df369a03652c6331153650e72a21d768355d1fe994ca2917f462ae8161b1dc13605fb121aab94a5a840cca35634b-78970e7f9a01087f58c7d9d84259b23d";
    const benchUrl = "https://sdeuc1.eu-central-1.shapediver.com";
    
    const shelfTicket = 'bdf4391107cb5bf8c8bc941193ee42f52d3cfedbddf4fc8bb8bb42c7112de5efa3c13d218c1a723acf11f056e7db5086445c8b0d765029c550df369a03652c6331153650e72a21d768355d1fe994ca2917f462ae8161b1dc13605fb121aab94a5a840cca35634b-78970e7f9a01087f58c7d9d84259b23d';
    const shelfUrl = 'https://sdeuc1.eu-central-1.shapediver.com';
    
    const [ticket, setTicket] = useState(benchTicket);
    const [modelViewUrl, setModelViewUrl] = useState(benchUrl);

    const loadShapediverViewport = async () => {
        const viewport = await createViewport({
            canvas: document.getElementById("canvas") as HTMLCanvasElement,
            id: "myViewport",
        });
    };

    useEffect(() => {
        loadShapediverViewport();
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Manglar Madre Design Explorer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.header}>
                <div className={styles.title}>
                    Welcome to{" "}
                    <a href="https://en.wikipedia.org/wiki/Tulum">
                        Manglar Madre
                    </a>
                </div>
            </div>
            <div className={styles.gridLayout}>
                <div className={styles.canvasContainer}>
                    <canvas className={styles.canvas} id="canvas"></canvas>
                </div>
                <div className={styles.inputsContainer}>
                    <SdSession
                        ticket={ticket}
                        modelViewUrl={modelViewUrl}
                    >
                        {/* 
                        TODO: Additional components to pull in from the example if we want to enable model interaction
                        <SdSessionInteractionData level={interactionLevel} interactionTypes={interactionTypes}/>
                        <SdSessionParameterBridge/>
                        <SdSessionParameterPanel/> 
                    */}
                        <SdSessionInputs/>
                    </SdSession>
                </div>
            </div>
            <div className={styles.tableContainer}> Future Table Container </div>
        </div>
    );
}
